package com.example.interviewpractice

import android.Manifest
import android.app.Activity
import android.content.Intent
import android.content.SharedPreferences
import android.content.pm.PackageManager
import android.graphics.Color
import android.graphics.PorterDuff
import android.graphics.drawable.GradientDrawable
import android.os.Bundle
import android.os.Handler
import android.speech.RecognitionListener
import android.speech.RecognizerIntent
import android.speech.SpeechRecognizer
import android.view.Gravity
import android.view.View
import android.view.animation.Animation
import android.view.animation.TranslateAnimation
import android.widget.*
import java.util.Locale

data class Q(val question:String,val answer:String,val keywords:List<String>)
data class Attempt(val questionIndex:Int,val spoken:String,val marks:Int)

class MainActivity:Activity(){
 private val questions=listOf(
  Q("What is Selenium WebDriver?","Selenium WebDriver is an API used to automate web browsers.",listOf("selenium","webdriver","automate","browser")),
  Q("What is XPath?","XPath is a locator used to identify elements in an HTML or XML document.",listOf("xpath","locator","element")),
  Q("What is an explicit wait?","An explicit wait waits for a specific condition before continuing.",listOf("explicit","wait","condition")),
  Q("What is TestNG?","TestNG is a Java testing framework used to organize and execute automated tests.",listOf("testng","testing","framework","java")),
  Q("What is Page Object Model?","POM keeps page locators and page actions inside page classes.",listOf("page","object","model","locator","action")),
  Q("What is SQL?","SQL is a language used to query and manage relational database data.",listOf("sql","query","database")),
  Q("What is an API?","An API is an interface that allows software systems to communicate.",listOf("api","interface","communicate"))
 )
 private var index=0;private var total=0;private var answered=0;private var listening=false;private var finishing=false
 private var spokenText=StringBuilder();private var recognizer:SpeechRecognizer?=null;private val attempts=mutableListOf<Attempt>();private val handler=Handler(mainLooper)
 private lateinit var prefs:SharedPreferences;private lateinit var root:LinearLayout;private lateinit var qText:TextView;private lateinit var result:TextView;private lateinit var score:TextView;private lateinit var speak:Button;private lateinit var progress:ProgressBar
 override fun onCreate(b:Bundle?){super.onCreate(b);prefs=getSharedPreferences("settings",MODE_PRIVATE);showHome()}
 private fun primary()=prefs.getInt("primary",Color.rgb(78,93,210));private fun bg()=prefs.getInt("background",Color.rgb(242,245,255));private fun qColor()=prefs.getInt("qcolor",Color.rgb(31,41,84));private fun myColor()=prefs.getInt("mycolor",Color.rgb(35,110,190));private fun rightColor()=prefs.getInt("rightcolor",Color.rgb(30,145,90))
 private fun baseLayout()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(26,26,26,26);background=getDrawable(com.example.interviewpractice.R.drawable.books_background);background?.setColorFilter(bg(),PorterDuff.Mode.SRC_ATOP);background?.alpha=235}
 private fun title(t:String,s:Float=26f)=TextView(this).apply{text=t;textSize=s;setTextColor(qColor());setPadding(0,8,0,16);gravity=Gravity.CENTER}
 private fun card(t:String,s:Float=17f)=TextView(this).apply{text=t;textSize=s;setTextColor(Color.rgb(35,42,60));setPadding(22,22,22,22);background=GradientDrawable().apply{setColor(Color.argb(235,255,255,255));cornerRadius=28f;setStroke(2,primary())};elevation=7f}
 private fun button(t:String)=Button(this).apply{text=t;textSize=16f;isAllCaps=false;setTextColor(Color.WHITE);background=GradientDrawable().apply{setColor(primary());cornerRadius=28f};setPadding(14,10,14,10);elevation=5f}
 private fun animateIn(v:View){if(!prefs.getBoolean("animation",true)){v.alpha=1f;return};v.alpha=0f;v.translationY=22f;v.animate().alpha(1f).translationY(0f).setDuration(420).start()}
 private fun animatedGirl():TextView=TextView(this).apply{text="👩‍💻✨";textSize=42f;gravity=Gravity.CENTER;setPadding(0,4,0,8);if(prefs.getBoolean("animation",true)){val a=TranslateAnimation(-45f,45f,0f,0f);a.duration=1500;a.repeatMode=Animation.REVERSE;a.repeatCount=Animation.INFINITE;startAnimation(a)}}
 private fun books():TextView=TextView(this).apply{text="📚  📖  📕  📗  📘  📙  📚";textSize=25f;gravity=Gravity.CENTER;setTextColor(primary())}
 private fun showHome(){root=baseLayout();root.addView(books());root.addView(animatedGirl());root.addView(title("🎯 Interview Practice",30f));root.addView(title("Practice • Speak • Review • Improve",18f));val test=button("🎤  Start Test");val list=button("📚  All Questions & Answers");val review=button("📝  Review My Answers");val settings=button("⚙️  Settings");val clear=button("🗑️  Clear My Results");listOf(test,list,review,settings,clear).forEach{root.addView(it);(it.layoutParams as LinearLayout.LayoutParams).setMargins(0,7,0,7);animateIn(it)};root.addView(title("✨ Learn • Speak • Improve • Repeat ✨",15f));setContentView(root);test.setOnClickListener{showTest()};list.setOnClickListener{showQuestionList()};review.setOnClickListener{showReview()};settings.setOnClickListener{showSettings()};clear.setOnClickListener{attempts.clear();total=0;answered=0;Toast.makeText(this,"Results cleared",Toast.LENGTH_SHORT).show();showHome()}}
 private fun colorChoice(label:String,key:String,c:Int){val b=button(label);b.setOnClickListener{prefs.edit().putInt(key,c).apply();showSettings()};root.addView(b);animateIn(b)}
 private fun showSettings(){root=baseLayout();val home=button("←  Home");root.addView(home);home.setOnClickListener{showHome()};root.addView(animatedGirl());root.addView(title("⚙️ Settings",28f));root.addView(title("Choose any look you like",18f));root.addView(title("Main colour",16f));listOf("🔵 Blue" to Color.rgb(78,93,210),"🟣 Purple" to Color.rgb(125,82,190),"🟢 Green" to Color.rgb(35,145,100),"🟠 Orange" to Color.rgb(225,125,45),"🌸 Pink" to Color.rgb(205,75,135),"🔴 Red" to Color.rgb(205,55,65)).forEach{colorChoice(it.first,"primary",it.second)};root.addView(title("Full-screen background",16f));listOf("☁️ Soft Blue" to Color.rgb(205,220,255),"🌙 Dark" to Color.rgb(35,38,50),"🌿 Green" to Color.rgb(205,240,218),"🌸 Pink" to Color.rgb(255,210,232),"🌊 Sky" to Color.rgb(190,225,255),"🌅 Cream" to Color.rgb(255,230,180)).forEach{colorChoice(it.first,"background",it.second)};root.addView(title("Question / My Answer / Correct Answer",16f));listOf("Question: Blue" to Pair("qcolor",Color.rgb(31,80,170)),"My Answer: Orange" to Pair("mycolor",Color.rgb(210,105,35)),"Correct Answer: Green" to Pair("rightcolor",Color.rgb(30,145,90))).forEach{colorChoice(it.first,it.second.first,it.second.second)};val anim=Switch(this).apply{text="✨ Animations + moving girl";textSize=17f;isChecked=prefs.getBoolean("animation",true);setPadding(0,20,0,20)};root.addView(anim);anim.setOnCheckedChangeListener{_,c->prefs.edit().putBoolean("animation",c).apply()};root.addView(card("🎤 Voice improvements\n\n• 3-second silence completes the answer.\n• Partial speech is shown while you talk.\n• If recognition has a temporary error, the app retries automatically.\n• Speak for longer answers without pressing Done.\n\nNote: the tiny speech-recognition beep is controlled by Android's speech service, not by this app."));val done=button("✅  Save & Home");root.addView(done);done.setOnClickListener{showHome()};setContentView(root)}
 private fun showTest(){root=baseLayout();val home=button("←  Home");root.addView(home);home.setOnClickListener{stopListening();showHome()};score=title("⭐ Score: $total",18f);root.addView(score);progress=ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.max=questions.size;progress.progress=answered.coerceAtMost(questions.size);root.addView(progress);qText=card("");root.addView(qText);animateIn(qText);speak=button("🎤  Start Speaking");root.addView(speak);animateIn(speak);result=card("");root.addView(result);result.visibility=View.GONE;val next=button("➡️  Next Question");root.addView(next);setContentView(root);showQuestion();speak.setOnClickListener{if(listening)finishAnswer() else startListening()};next.setOnClickListener{stopListening();index=(index+1)%questions.size;result.text="";result.visibility=View.GONE;showQuestion()}}
 private fun showQuestionList(){val scroll=ScrollView(this);val list=baseLayout();val home=button("←  Home");list.addView(home);home.setOnClickListener{showHome()};list.addView(books());list.addView(title("📚 Questions & Answers",26f));questions.forEachIndexed{i,q->val c=card("Q${i+1}. ${q.question}\n\nAnswer: ${q.answer}");list.addView(c);animateIn(c);c.setOnClickListener{index=i;showTest()}};scroll.addView(list);setContentView(scroll)}
 private fun showReview(){val scroll=ScrollView(this);val list=baseLayout();val home=button("←  Home");list.addView(home);home.setOnClickListener{showHome()};list.addView(animatedGirl());list.addView(title("📝 My Answer Review",26f));if(attempts.isEmpty())list.addView(title("No answers yet. Start a test first.",18f));attempts.forEach{a->val q=questions[a.questionIndex];val c=card("Q${a.questionIndex+1}. ${q.question}\n\n🗣️ YOUR ANSWER\n${a.spoken.ifBlank{"(No answer detected)"}}\n\n⭐ SCORE: ${a.marks}/10\n\n✅ CORRECT ANSWER\n${q.answer}");list.addView(c);animateIn(c)};scroll.addView(list);setContentView(scroll)}
 private fun showQuestion(){qText.text="Q${index+1}\n\n${questions[index].question}";score.text="⭐ Score: $total   •   Answered: $answered/${questions.size}";progress.progress=answered.coerceAtMost(questions.size);speak.isEnabled=true;speak.text="🎤  Start Speaking"}
 private fun startListening(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(arrayOf(Manifest.permission.RECORD_AUDIO),200);return};if(!SpeechRecognizer.isRecognitionAvailable(this)){result.visibility=View.VISIBLE;result.text="Speech recognition available nahi hai.";return};recognizer?.destroy();recognizer=SpeechRecognizer.createSpeechRecognizer(this);recognizer!!.setRecognitionListener(object:RecognitionListener{override fun onReadyForSpeech(p:Bundle?){result.visibility=View.VISIBLE;result.text="🎧 Ready... ab answer bolo."};override fun onBeginningOfSpeech(){listening=true;result.text="🎧 Sun raha hoon... bolte raho."};override fun onRmsChanged(r:Float){};override fun onBufferReceived(b:ByteArray?){};override fun onEndOfSpeech(){result.text="⏳ Sunna complete... answer process ho raha hai."};override fun onError(e:Int){if(finishing||!listening)return;handler.postDelayed({if(listening&&!finishing)startRecognition()},500)};override fun onResults(d:Bundle?){val t=d?.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION)?.firstOrNull().orEmpty();if(t.isNotBlank())spokenText.append(" ").append(t);if(spokenText.isNotBlank())finishAnswer()else if(!finishing)handler.postDelayed({if(listening&&!finishing)startRecognition()},500)};override fun onPartialResults(d:Bundle?){val t=d?.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION)?.firstOrNull().orEmpty();if(t.isNotBlank()){result.visibility=View.VISIBLE;result.text="🎧 $t\n\nKeep speaking..."}};override fun onEvent(t:Int,p:Bundle?){}});finishing=false;listening=true;spokenText.clear();speak.text="⏹️ Listening...";result.visibility=View.VISIBLE;result.text="🎧 Ready...";startRecognition()}
 private fun startRecognition(){try{recognizer?.startListening(Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).apply{putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);putExtra(RecognizerIntent.EXTRA_LANGUAGE,Locale.ENGLISH);putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,true);putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_COMPLETE_SILENCE_LENGTH_MILLIS,3000L);putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_POSSIBLY_COMPLETE_SILENCE_LENGTH_MILLIS,3000L);putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_MINIMUM_LENGTH_MILLIS,5000L);putExtra(RecognizerIntent.EXTRA_MAX_RESULTS,1)})}catch(_:Exception){}}
 private fun finishAnswer(){if(finishing)return;finishing=true;listening=false;speak.text="🎤 Start Speaking";try{recognizer?.stopListening()}catch(_:Exception){};evaluate(spokenText.toString().trim())}
 private fun stopListening(){finishing=true;listening=false;try{recognizer?.stopListening();recognizer?.destroy()}catch(_:Exception){};recognizer=null}
 private fun evaluate(spoken:String){val s=spoken.lowercase();val hits=questions[index].keywords.count{s.contains(it)};val pct=if(questions[index].keywords.isEmpty())0 else hits*100/questions[index].keywords.size;val marks=when{pct>=75->10;pct>=50->7;pct>=25->4;else->1};total+=marks;answered++;attempts.add(Attempt(index,spoken,marks));val verdict=if(marks>=9)"🏆 BEST! Excellent answer"else if(marks>=7)"🌟 VERY GOOD!"else if(marks>=4)"👍 GOOD START - Improve a little"else"💪 Keep practicing - You will improve";result.visibility=View.VISIBLE;result.text="🗣️ YOUR ANSWER\n$spoken\n\n$verdict\n⭐ How correct: $marks/10\n\n✅ CORRECT ANSWER\n${questions[index].answer}";result.setTextColor(myColor());result.animate().alpha(1f).setDuration(450).start();score.text="⭐ Score: $total   •   Answered: $answered/${questions.size}";progress.progress=answered.coerceAtMost(questions.size)}
 override fun onRequestPermissionsResult(r:Int,p:Array<out String>,g:IntArray){super.onRequestPermissionsResult(r,p,g);if(r==200&&g.isNotEmpty()&&g[0]==PackageManager.PERMISSION_GRANTED)startListening()};override fun onDestroy(){stopListening();super.onDestroy()}
}
