package com.example.interviewpractice
import android.Manifest
import android.app.Activity
import android.content.*
import android.content.pm.PackageManager
import android.graphics.Color
import android.graphics.drawable.GradientDrawable
import android.os.*
import android.speech.*
import android.view.*
import android.view.animation.*
import android.widget.*
import java.util.Locale

class MainActivity:Activity(){
 private val qs by lazy{QuestionBank.all}; private var i=0;private var total=0;private var answered=0
 private var listening=false;private var finishing=false;private var spoken=StringBuilder();private var sr:SpeechRecognizer?=null
 private val attempts=mutableListOf<String>();private lateinit var h:Handler;private lateinit var p:SharedPreferences
 private lateinit var root:LinearLayout;private lateinit var qv:TextView;private lateinit var out:TextView;private lateinit var sv:TextView;private lateinit var mic:Button
 data class Attempt(val i:Int,val text:String,val mark:Int)
 private val history=mutableListOf<Attempt>()
 override fun onCreate(b:Bundle?){super.onCreate(b);h=Handler(Looper.getMainLooper());p=getSharedPreferences("settings",MODE_PRIVATE);home()}
 private fun pri()=p.getInt("primary",Color.rgb(78,93,210));private fun bg()=p.getInt("background",Color.rgb(242,245,255));private fun tc()=p.getInt("qcolor",Color.rgb(31,41,84))
 private fun lay()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(22,22,22,22);setBackgroundColor(bg())}
 private fun t(s:String,n:Float=24f)=TextView(this).apply{text=s;textSize=n;setTextColor(tc());gravity=Gravity.CENTER;setPadding(4,8,4,14)}
 private fun b(s:String)=Button(this).apply{text=s;textSize=16f;isAllCaps=false;setTextColor(Color.WHITE);background=GradientDrawable().apply{setColor(pri());cornerRadius=26f};elevation=4f}
 private fun c(s:String)=TextView(this).apply{text=s;textSize=17f;setTextColor(Color.DKGRAY);setPadding(18,18,18,18);background=GradientDrawable().apply{setColor(Color.WHITE);cornerRadius=22f;setStroke(2,pri())}}
 private fun add(v:View){root.addView(v)}
 private fun girl()=TextView(this).apply{text="👩‍💻✨";textSize=40f;gravity=Gravity.CENTER;if(p.getBoolean("animation",true)){val a=TranslateAnimation(-30f,30f,0f,0f);a.duration=1600;a.repeatMode=Animation.REVERSE;a.repeatCount=-1;startAnimation(a)}}
 private fun home(){root=lay();add(t("📚 🎯 📖",24f));add(girl());add(t("Interview Practice",30f));add(t("Practice • Speak • Review • Exam",17f));val x=b("🎤 Speaking Test");val e=b("📝 EXAM MODE");val q=b("📚 All ${qs.size} Questions & Answers");val z=b("⚡ Selenium One-Line Code");val r=b("📝 Review My Answers");val s=b("⚙️ Settings");val cl=b("🗑️ Clear Results");listOf(x,e,q,z,r,s,cl).forEach{add(it)};setContentView(root);x.setOnClickListener{speaking()};e.setOnClickListener{examSetup()};q.setOnClickListener{bank()};z.setOnClickListener{quick()};r.setOnClickListener{review()};s.setOnClickListener{settings()};cl.setOnClickListener{history.clear();total=0;answered=0;Toast.makeText(this,"Results cleared",Toast.LENGTH_SHORT).show();home()}}
 private fun bank(){val sc=ScrollView(this);root=lay();add(b("← Home").also{it.setOnClickListener{home()}});add(t("📚 ${qs.size} Interview Questions",27f));qs.forEachIndexed{n,q->val v=c("${n+1}. [${q.category}] ${q.question}\n\n💡 ${q.answer}${if(q.code.isNotBlank())"\n\n⚡ ${q.code}"else""}");add(v);v.setOnClickListener{i=n;speaking()}};sc.addView(root);setContentView(sc)}
 private fun quick(){val sc=ScrollView(this);root=lay();add(b("← Home").also{it.setOnClickListener{home()}});add(t("⚡ Selenium One-Line Code",27f));qs.filter{it.category=="Selenium"&&it.code.isNotBlank()}.distinctBy{it.code}.forEach{add(c("${it.question}\n\n${it.code}\n\n💡 ${it.answer}"))};sc.addView(root);setContentView(sc)}
 private fun speaking(){root=lay();add(b("← Home").also{it.setOnClickListener{stop();home()}});sv=t("⭐ Score: $total",17f);add(sv);qv=c("");add(qv);mic=b("🎤 Start Speaking");add(mic);out=c("");root.addView(out);out.visibility=View.GONE;add(b("➡️ Next Question").also{it.setOnClickListener{stop();i=(i+1)%qs.size;showQ()}});setContentView(root);showQ();mic.setOnClickListener{if(listening)finishAnswer()else listen()}}
 private fun showQ(){val q=qs[i];qv.text="Q${i+1} [${q.category}]\n\n${q.question}";sv.text="⭐ Score: $total  •  Answered: $answered";mic.text="🎤 Start Speaking"}
 private fun listen(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(arrayOf(Manifest.permission.RECORD_AUDIO),7);return};if(!SpeechRecognizer.isRecognitionAvailable(this)){out.visibility=View.VISIBLE;out.text="Speech recognition unavailable.";return};try{sr?.destroy();sr=SpeechRecognizer.createSpeechRecognizer(this);sr!!.setRecognitionListener(listener);spoken.clear();finishing=false;listening=true;mic.text="⏹ Listening...";out.visibility=View.VISIBLE;out.text="🎧 Ready... speak your complete answer.";start()}catch(_:Exception){out.text="Voice could not start. Try again."}}
 private val listener=object:RecognitionListener{override fun onReadyForSpeech(x:Bundle?){out.text="🎧 Ready..."};override fun onBeginningOfSpeech(){out.text="🎧 Listening..."};override fun onRmsChanged(x:Float){};override fun onBufferReceived(x:ByteArray?){};override fun onEndOfSpeech(){};override fun onError(x:Int){if(listening&&!finishing)h.postDelayed({start()},500)};override fun onPartialResults(x:Bundle?){x?.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION)?.firstOrNull()?.let{out.text="🎧 $it\n\nKeep speaking..."}};override fun onResults(x:Bundle?){x?.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION)?.firstOrNull()?.let{spoken.append(" ").append(it)};if(spoken.isNotBlank())h.postDelayed({if(!finishing)finishAnswer()},300)};override fun onEvent(a:Int,b:Bundle?){} }
 private fun start(){try{sr?.startListening(Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).apply{putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);putExtra(RecognizerIntent.EXTRA_LANGUAGE,Locale.ENGLISH);putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,true);putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_COMPLETE_SILENCE_LENGTH_MILLIS,3000L);putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_POSSIBLY_COMPLETE_SILENCE_LENGTH_MILLIS,3000L);putExtra(RecognizerIntent.EXTRA_SPEECH_INPUT_MINIMUM_LENGTH_MILLIS,3000L)})}catch(_:Exception){}}
 private fun finishAnswer(){if(finishing)return;finishing=true;listening=false;try{sr?.stopListening()}catch(_:Exception){};val q=qs[i];val s=spoken.toString().lowercase();val hit=q.keywords.count{s.contains(it)};val pct=if(q.keywords.isEmpty())0 else hit*100/q.keywords.size;val mark=when{pct>=75->10;pct>=50->7;pct>=25->4;else->1};total+=mark;answered++;history.add(Attempt(i,spoken.toString(),mark));out.visibility=View.VISIBLE;out.text="🗣️ YOUR ANSWER\n${spoken.toString().trim()}\n\n⭐ $mark/10  ${if(mark>=9)"🏆 BEST!"else if(mark>=7)"🌟 VERY GOOD!"else if(mark>=4)"👍 GOOD START"else"💪 KEEP PRACTICING"}\n\n✅ CORRECT ANSWER\n${q.answer}${if(q.code.isNotBlank())"\n\n⚡ ONE-LINE CODE\n${q.code}"else""}";sv.text="⭐ Score: $total  •  Answered: $answered"}
 private fun stop(){finishing=true;listening=false;try{sr?.stopListening();sr?.destroy()}catch(_:Exception){};sr=null}
 private fun review(){val sc=ScrollView(this);root=lay();add(b("← Home").also{it.setOnClickListener{home()}});add(t("📝 My Answers",27f));if(history.isEmpty())add(t("No attempts yet.",18f));history.forEach{a->val q=qs[a.i];add(c("Q${a.i+1}. ${q.question}\n\n🗣️ YOUR ANSWER\n${a.text.ifBlank{"No answer detected"}}\n\n⭐ ${a.mark}/10\n\n✅ CORRECT ANSWER\n${q.answer}"))};sc.addView(root);setContentView(sc)}
 private var exam=emptyList<BankItem>();private var ep=0;private var ec=0;private var timer:CountDownTimer?=null;private lateinit var eq:TextView;private lateinit var es:TextView;private lateinit var next:Button
 private fun examSetup(){root=lay();add(b("← Home").also{it.setOnClickListener{home()}});add(girl());add(t("📝 Exam Mode",29f));add(t("Choose size",18f));listOf(20,50,100).forEach{n->add(b("$n Questions").also{x->x.setOnClickListener{startExam(n)}})};add(c("20 Q = 20 min\n50 Q = 45 min\n100 Q = 90 min\n\nTopics: Java, Selenium, TestNG, Framework, Maven, Git, CI/CD, API, SQL, Testing."));setContentView(root)}
 private fun startExam(n:Int){exam=qs.shuffled().take(n);ep=0;ec=0;root=lay();add(b("✕ Exit").also{it.setOnClickListener{timer?.cancel();home()}});es=t("Question 1/$n • Score 0",17f);add(es);eq=c("");add(eq);val opts=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};add(opts);next=b("Next");add(next);setContentView(root);render(opts);val mins=if(n<=20)20L else if(n<=50)45L else 90L;timer=object:CountDownTimer(mins*60000,1000){override fun onTick(ms:Long){es.text="Question ${ep+1}/$n • Score $ec • ⏱️ ${ms/60000}:${String.format("%02d",(ms/1000)%60)}"};override fun onFinish(){finishExam()}}.start()}
 private fun render(opts:LinearLayout){opts.removeAllViews();val q=exam[ep];eq.text="[${q.category}]\n\n${q.question}";val answers=(listOf(q.answer)+qs.filter{it.question!=q.question}.shuffled().take(3).map{it.answer}).shuffled();answers.forEach{a->val x=b(a);opts.addView(x);x.setOnClickListener{opts.forEach{v->v.isEnabled=false};if(a==q.answer){ec++;x.text="✅ $a"}else x.text="❌ $a";next.text=if(ep==exam.lastIndex)"Submit Exam"else"Next"}};next.setOnClickListener{if(ep==exam.lastIndex)finishExam()else{ep++;render(opts)}}}
 private fun finishExam(){timer?.cancel();val pct=ec*100/exam.size;root=lay();add(girl());add(t("🏆 Exam Complete",30f));add(t("$ec / ${exam.size}",38f));add(t("$pct%",30f));add(c(if(pct>=90)"🏆 Excellent!"else if(pct>=75)"🌟 Very Good!"else if(pct>=60)"👍 Good progress!"else"💪 Keep practicing!"));add(b("← Home").also{it.setOnClickListener{home()}});setContentView(root)}
 private fun settings(){root=lay();add(b("← Home").also{it.setOnClickListener{home()}});add(girl());add(t("⚙️ Settings",28f));listOf("🔵 Blue" to Color.rgb(78,93,210),"🟣 Purple" to Color.rgb(125,82,190),"🟢 Green" to Color.rgb(35,145,100),"🟠 Orange" to Color.rgb(225,125,45),"🌸 Pink" to Color.rgb(205,75,135),"🔴 Red" to Color.rgb(205,55,65)).forEach{(n,c)->add(b(n).also{x->x.setOnClickListener{p.edit().putInt("primary",c).apply();settings()}})};add(t("Background colour",17f));listOf("☁️ Blue" to Color.rgb(205,220,255),"🌙 Dark" to Color.rgb(35,38,50),"🌿 Green" to Color.rgb(205,240,218),"🌸 Pink" to Color.rgb(255,210,232),"🌊 Sky" to Color.rgb(190,225,255),"🌅 Cream" to Color.rgb(255,230,180),"⚪ White" to Color.WHITE).forEach{(n,c)->add(b(n).also{x->x.setOnClickListener{p.edit().putInt("background",c).apply();settings()}})};add(Switch(this).apply{text="✨ Animation + moving girl";isChecked=p.getBoolean("animation",true);setOnCheckedChangeListener{_,v->p.edit().putBoolean("animation",v).apply()}});add(c("Question = blue • Your Answer = orange • Correct Answer = green\nVoice automatically completes after about 3 seconds of silence."));add(b("Save & Home").also{it.setOnClickListener{home()}});setContentView(root)}
 override fun onRequestPermissionsResult(r:Int,a:Array<out String>,g:IntArray){super.onRequestPermissionsResult(r,a,g);if(r==7&&g.isNotEmpty()&&g[0]==PackageManager.PERMISSION_GRANTED)listen()};override fun onDestroy(){stop();timer?.cancel();super.onDestroy()}
}
