package com.example.interviewpractice

data class QuickCode(val topic:String,val code:String,val use:String)

val seleniumQuickCodes = listOf(
 QuickCode("Launch browser","WebDriver driver = new ChromeDriver();","Open Chrome browser"),
 QuickCode("Open URL","driver.get(\"https://example.com\");","Navigate to a URL"),
 QuickCode("Find by ID","driver.findElement(By.id(\"login\"));","Locate element by id"),
 QuickCode("Find by Name","driver.findElement(By.name(\"username\"));","Locate element by name"),
 QuickCode("Find by Class","driver.findElement(By.className(\"btn\"));","Locate element by class"),
 QuickCode("Find by CSS","driver.findElement(By.cssSelector(\"input#user\"));","Locate using CSS"),
 QuickCode("Find by XPath","driver.findElement(By.xpath(\"//input[@id='user']\"));","Locate using XPath"),
 QuickCode("Click","element.click();","Click an element"),
 QuickCode("Type text","element.sendKeys(\"admin\");","Enter text"),
 QuickCode("Clear text","element.clear();","Clear an input"),
 QuickCode("Get text","String text = element.getText();","Read visible text"),
 QuickCode("Get attribute","String value = element.getAttribute(\"value\");","Read an HTML attribute"),
 QuickCode("Displayed","element.isDisplayed();","Check visibility"),
 QuickCode("Enabled","element.isEnabled();","Check enabled state"),
 QuickCode("Selected","element.isSelected();","Check selected state"),
 QuickCode("Implicit wait","driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));","Global wait"),
 QuickCode("Explicit wait","new WebDriverWait(driver, Duration.ofSeconds(10)).until(ExpectedConditions.visibilityOf(element));","Wait for a condition"),
 QuickCode("Fluent wait","new FluentWait<>(driver).withTimeout(Duration.ofSeconds(10)).pollingEvery(Duration.ofMillis(500));","Custom polling wait"),
 QuickCode("Mouse hover","new Actions(driver).moveToElement(element).perform();","Hover over an element"),
 QuickCode("Double click","new Actions(driver).doubleClick(element).perform();","Double-click"),
 QuickCode("Right click","new Actions(driver).contextClick(element).perform();","Context click"),
 QuickCode("Drag and drop","new Actions(driver).dragAndDrop(source, target).perform();","Drag one element to another"),
 QuickCode("Key press","new Actions(driver).sendKeys(Keys.ENTER).perform();","Press a keyboard key"),
 QuickCode("Dropdown by text","new Select(element).selectByVisibleText(\"India\");","Select an option"),
 QuickCode("Dropdown by value","new Select(element).selectByValue(\"IN\");","Select by option value"),
 QuickCode("Dropdown by index","new Select(element).selectByIndex(1);","Select by index"),
 QuickCode("Switch to frame","driver.switchTo().frame(element);","Enter an iframe"),
 QuickCode("Default content","driver.switchTo().defaultContent();","Return from iframe"),
 QuickCode("Parent frame","driver.switchTo().parentFrame();","Move to parent frame"),
 QuickCode("Window handle","String handle = driver.getWindowHandle();","Get current window handle"),
 QuickCode("All window handles","Set<String> handles = driver.getWindowHandles();","Get all window handles"),
 QuickCode("Switch window","driver.switchTo().window(handle);","Switch to another window"),
 QuickCode("Accept alert","driver.switchTo().alert().accept();","Accept JavaScript alert"),
 QuickCode("Dismiss alert","driver.switchTo().alert().dismiss();","Dismiss alert"),
 QuickCode("Alert text","driver.switchTo().alert().getText();","Read alert message"),
 QuickCode("Alert input","driver.switchTo().alert().sendKeys(\"text\");","Type into prompt"),
 QuickCode("Screenshot","((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);","Capture screenshot"),
 QuickCode("JavaScript click","((JavascriptExecutor)driver).executeScript(\"arguments[0].click();\", element);","Click with JavaScript"),
 QuickCode("JavaScript scroll","((JavascriptExecutor)driver).executeScript(\"arguments[0].scrollIntoView(true);\", element);","Scroll to element"),
 QuickCode("Page title","driver.getTitle();","Get page title"),
 QuickCode("Current URL","driver.getCurrentUrl();","Get current URL"),
 QuickCode("Refresh","driver.navigate().refresh();","Refresh page"),
 QuickCode("Back","driver.navigate().back();","Go back"),
 QuickCode("Forward","driver.navigate().forward();","Go forward"),
 QuickCode("Maximize","driver.manage().window().maximize();","Maximize browser"),
 QuickCode("Close tab","driver.close();","Close current window"),
 QuickCode("Quit browser","driver.quit();","Close all browser windows"),
 QuickCode("Find multiple","driver.findElements(By.cssSelector(\".item\"));","Find multiple elements"),
 QuickCode("Get tag name","element.getTagName();","Read element tag"),
 QuickCode("Get CSS value","element.getCssValue(\"color\");","Read CSS property"),
 QuickCode("Scroll page","((JavascriptExecutor)driver).executeScript(\"window.scrollBy(0,500);\");","Scroll page down"),
 QuickCode("Move to element","new Actions(driver).moveToElement(element).perform();","Move mouse to element"),
 QuickCode("Build locator","By.id(\"username\");","Create a reusable locator"),
 QuickCode("TestNG test","@Test public void loginTest() { }","Mark a TestNG test"),
 QuickCode("Before method","@BeforeMethod public void setup() { }","Run before each test"),
 QuickCode("After method","@AfterMethod public void tearDown() { }","Run after each test"),
 QuickCode("Assert equals","Assert.assertEquals(actual, expected);","Compare expected and actual"),
 QuickCode("Assert true","Assert.assertTrue(condition);","Verify condition is true"),
 QuickCode("Assert false","Assert.assertFalse(condition);","Verify condition is false"),
 QuickCode("Assert not null","Assert.assertNotNull(value);","Verify object is not null"),
 QuickCode("Java String compare","actual.equals(expected);","Compare String values"),
 QuickCode("List size","list.size();","Get collection size"),
 QuickCode("Loop elements","for (WebElement e : elements) { e.getText(); }","Iterate WebElements"),
 QuickCode("Wait clickable","new WebDriverWait(driver, Duration.ofSeconds(10)).until(ExpectedConditions.elementToBeClickable(element));","Wait until clickable"),
 QuickCode("Wait title","new WebDriverWait(driver, Duration.ofSeconds(10)).until(ExpectedConditions.titleContains(\"Home\"));","Wait for title"),
 QuickCode("Wait URL","new WebDriverWait(driver, Duration.ofSeconds(10)).until(ExpectedConditions.urlContains(\"dashboard\"));","Wait for URL"),
 QuickCode("Wait invisible","new WebDriverWait(driver, Duration.ofSeconds(10)).until(ExpectedConditions.invisibilityOf(element));","Wait until hidden"),
 QuickCode("Wait presence","new WebDriverWait(driver, Duration.ofSeconds(10)).until(ExpectedConditions.presenceOfElementLocated(By.id(\"user\")));","Wait for DOM presence"),
 QuickCode("Switch first window","driver.switchTo().window(driver.getWindowHandles().iterator().next());","Switch using a handle"),
 QuickCode("Cookie add","driver.manage().addCookie(new Cookie(\"name\",\"value\"));","Add a browser cookie"),
 QuickCode("Cookie delete","driver.manage().deleteCookieNamed(\"name\");","Delete a cookie"),
 QuickCode("Get cookies","driver.manage().getCookies();","Read cookies")
)
